// Action Types
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const ADD_BOOK_ERROR = 'ADD_BOOK_ERROR';
export const DELETE_BOOK_ERROR = 'DELETE_BOOK_ERROR';
export const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR';
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
export const UPDATE_BOOK_ERROR = 'UPDATE_BOOK_ERROR';